// apps/cli/src/command/log/multi-day-slice-list.tsx
import type { Slice } from '@stayradiated/pomo-core'
import * as dateFns from 'date-fns'
import { toZonedTime } from 'date-fns-tz'
import { Box, Text } from 'ink'
import React from 'react'
import { SliceList } from './slice-list.js'
import type { SliceListProps } from './slice-list.js'

type MultiDaySliceListProps = SliceListProps

const MultiDaySliceList = (props: MultiDaySliceListProps) => {
  const { sliceList, timeZone } = props

  const sliceListByDay = sliceList.reduce<Map<string, Slice[]>>(
    (acc, slice) => {
      const { startedAt: startedAtUTC } = slice
      const startedAt = toZonedTime(startedAtUTC, timeZone)

      // Format as Friday 02 June 2023
      const day = dateFns.format(startedAt, 'EEEE dd MMMM yyyy')
      const list: Slice[] = acc.get(day) ?? []
      list.push(slice)
      acc.set(day, list)
      return acc
    },
    new Map(),
  )

  return (
    <>
      {Array.from(sliceListByDay.entries()).map(([day, sliceList]) => {
        return (
          <Box key={day} flexDirection="column" marginBottom={1}>
            <Text color="#888">{day}</Text>
            <SliceList {...props} sliceList={sliceList} />
          </Box>
        )
      })}
    </>
  )
}

export { MultiDaySliceList }
export type { MultiDaySliceListProps }

// apps/web/src/routes/MultiDaySliceList.svelte
<script lang="ts">
  import type { Stream, Point, Slice } from '@stayradiated/pomo-core';
  import { format } from 'date-fns'

  import SliceList from './SliceList.svelte'

  export let streamList: Stream[]
  export let pointList: Point[]
  export let sliceList: Slice[]

  const sliceListByDay = sliceList.reduce<Map<string, Slice[]>>(
    (acc, slice) => {
      // Format as Friday 02 June 2023
      const day = format(slice.startedAt, 'EEEE dd MMMM yyyy')
      const list: Slice[] = acc.get(day) ?? []
      list.push(slice)
      acc.set(day, list)
      return acc
    },
    new Map(),
  )
</script>

{#each Array.from(sliceListByDay.entries()) as [day, sliceList]}
  <div class="container">
    <p color="#888">{day}</p>
    <SliceList
      streamList={streamList}
      sliceList={sliceList}
      pointList={pointList}
    />
  </div>
{/each}

<style>
  .container {
    display: flex;
    flex-direction: column;
    margin-bottom: 1rem;
  }
</style>
